#!/bin/bash
PRINT=false
TOSTDERR=true
if [ "$1" == "-p" ] ; then
    PRINT=true
    TOSTDERR=true
    shift
elif [ "$1" == "-po" ] ; then
    PRINT=true
    TOSTDERR=false
    shift
fi
set -e
while read line ; do
    pushd "${line}" >/dev/null
    if $PRINT ; then
        if $TOSTDERR ; then
            pwd >&2
        else
            pwd
        fi
    fi
    eval "${*}"
    popd >/dev/null
done
