#!/bin/bash
if [[ $# == 2 ]]; then
  lower=$(($1 - 1))
  upper=$2
elif [[ $# == 1 ]]; then
  upper=$(($1 - 1))
  lower=-1
else
  lower=-1
  upper=-2
fi

i=$lower
while ((i != upper)); do
  i=$((i + 1))
  echo $i
done
